### PR TITLE
Migrate redirects from staging.bsky.app to bsky.app

### PR DESCRIPTION
**Pull request by ichthyos**
Noticed psky.app previews were still redirecting to staging.bsky.app. Let's migrate to bsky.app since the web app is now in production on that domain!

### CODE REVIEW

**Review by jasikpark — APPROVED** [review]
lgtm

**Comment by ichthyos** [comment]
@ianklatzco friendly ping :)

**Comment by ianklatzco** [comment]
sorry, been traveling! will peek at it monday 👀

**Comment by ianklatzco** [comment]
done! had to tweak the PR a bit, but things will now redirect to `bsky.app` instead of `staging.bsky.app`. thanks for waiting!

**Pull request closed without merging**
